version: "3"
services:
    w:
        build:
            context: ./
            dockerfile: Dockerfile
        hostname: "ubuntu-bionic"
        ports:
            - "7070:7070" # gdbserver
            - "7071:7071" # exeport
        volumes:
            - /opt/docker-share:/opt/docker-share:rw
        cap_add:
            - SYS_PTRACE
        security_opt:
            - seccomp:unconfined


# docker build -f Dockerfile -t gdbserver-ubuntu-18 .
# docker run --rm --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --volume "/home/wildfootw":"/home/wildfootw" --name gdbd-ubuntu-18 -it -P gdbserver-ubuntu-18 :56147 /home/wildfootw/b.out
# docker port gdbd-ubuntu-18
# <gdb> target remote localhost:32786 (return in docker port)
